Cargo.toml
crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-server/Cargo.toml
crates/hearth-server/src/main.rs

I added `hearth-client` and `hearth-server` crates with `tracing` logging, `clap` command line parameters, password authentication and encryption from `hearth-network`, and exchange of a `ClientApiClient` from the server to the client over Remoc.

Client and server binary targets

---

crates/hearth-client/src/main.rs
crates/hearth-cognito/Cargo.toml
crates/hearth-cognito/src/lib.rs
crates/hearth-rpc/src/lib.rs
crates/hearth-server/src/main.rs
crates/hearth-types/src/lib.rs

Overhauls basically all of `hearth-rpc` with a new peer-based API for exchanging `PeerProvider`s and `PeerApi`s.
Also adds a formal system for assigning peer IDs using a `ServerOffer` + `ClientOffer` exchange during initial client-server communication.
I've decided to remove trailing `...`s from log messages, such as in `Authenticating...` or `Binding...`. They don't really serve any real point. We may want to use Tracing spans for non-instantaneous operations, but that can be done in a future PR.

rpc: Peer-based API

---

Cargo.toml
crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-ipc/Cargo.toml
crates/hearth-ipc/src/lib.rs
crates/hearth-rpc/src/lib.rs
crates/hearth-server/Cargo.toml

'Nuff said.
Lots of IPC code was pulled from [Magpie](https://git.tebibyte.media/canary/canary-rs/src/branch/main/apps/magpie/src/service/ipc.rs). Thank you @airidaceae!
An IPC socket has been set up for the client, but not for the server. This is because a lot of code would need to be duplicated to set up a `PeerApiImpl` in the server code, too. This will be amended by #15.

Set up the `hearth-ipc` crate

---

Cargo.toml
crates/hearth-ctl/Cargo.toml
crates/hearth-ctl/src/main.rs
crates/hearth-ipc/src/lib.rs
crates/hearth-rpc/Cargo.toml

Adds a mostly-empty `hearth-ctl` crate for us to develop our Hearth CLI tools in.
Also, `hearth-rpc` was using remote collections even though that feature wasn't enabled on its Remoc dependency, so I fixed that.

Add `hearth-ctl` crate

---

crates/hearth-client/src/main.rs
crates/hearth-core/Cargo.toml
crates/hearth-core/src/api/lump_store.rs
crates/hearth-core/src/api/mod.rs
crates/hearth-core/src/lib.rs
crates/hearth-rpc/Cargo.toml
crates/hearth-rpc/src/lib.rs
crates/hearth-server/src/main.rs
crates/hearth-types/src/lib.rs

This adds a lump store RPC interface, an implementation of that in `hearth-core`, and some passing unit tests demonstrating how it's used.
I've also added the `ResourceError` and `ResourceResult` types to `hearth-rpc` for better error results in our RPC calls.
Read the commit messages for more goodies!

Add lump store

---

crates/hearth-core/src/asset.rs
crates/hearth-core/src/lump.rs
crates/hearth-core/src/runtime.rs

Makes `AssetStore` depend on a `LumpStoreImpl` and changes `AssetStore::load_asset()` from using a byte slice to using a lump ID instead.

core: lump asset loading

---

crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-ctl/Cargo.toml
crates/hearth-ctl/src/list_processes.rs
crates/hearth-ctl/src/main.rs
crates/hearth-server/Cargo.toml
crates/hearth-server/src/main.rs

Downgrade clap

---

Cargo.toml
crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-core/src/lib.rs
crates/hearth-core/src/pubsub.rs
crates/hearth-panels/Cargo.toml
crates/hearth-panels/src/lib.rs
crates/hearth-types/Cargo.toml
crates/hearth-types/src/lib.rs
crates/hearth-types/src/panels.rs

Adds the new `hearth-panels` crate for panel management and an extendable panel store, plus some process utilities like `PublisherService` and `impl_serialize_json_display`. Touches up `hearth-core` with `tokio` and `tracing` repubs. Defines an initial protocol for the paneling processes.

`hearth-panels`

---

crates/hearth-core/Cargo.toml
crates/hearth-core/src/process.rs

Closes #73.
I couldn't duplicate this behavior in a unit test, but I managed to trace the issue to downcasting entry keys given by the `sharded-slab` crate from a 64-bit `usize` to a 32-bit `LocalProcessId`. `sharded-slab` stored page info in the high-order 32 bits of a 64-bit key and that was getting discarded. Since we don't want bits in higher orders for process IDs for the sake of human readability, I just bit the performance bullet and swapped out `sharded-slab` for the slightly slower `RwLock`'d `slab::Slab`.

core: use non-sharded slab for processes

---

crates/hearth-core/src/process.rs
crates/hearth-rpc/src/lib.rs

Adding a `ProcessStatus` struct to help debug processes at runtime.
Also a necessary prerequisite for #56, since `hearth-ctl` needs to know the current length of the history in order to receive only the history in some modes.
- rpc: add ProcessStatus struct
- core: update process submodule to use ProcessStatus

rpc: add `ProcessStatus`

---

crates/hearth-client/Cargo.toml

Still needs testing to make sure that I didn't remove something essential.
Closes #111.

client: only enable winit x11 and wayland-dlopen features

---

README.md
crates/hearth-client/src/main.rs
crates/hearth-cognito/Cargo.toml
crates/hearth-cognito/src/lib.rs
crates/hearth-core/src/asset.rs
crates/hearth-core/src/process.rs
crates/hearth-core/src/runtime.rs
crates/hearth-ctl/src/spawn_wasm.rs
crates/hearth-server/src/main.rs

- `WasmProcessSpawner` receives `WasmSpawnInfo` messages and spawns `WasmProcess`s
- adds `ProcessContext::get_process_store()`
- add epoch-based yields to WebAssembly execution
- fixes an issue where `ctl`'s `spawn-wasm` command was not sending the message because it quits before the channel is flushed
- check off Wasm process spawning from roadmap
- return a Vec of `JoinHandle`s from `RuntimeBuilder::run()` so that runners and plugins can be aborted at the end of each binary

WebAssembly spawning

---

crates/hearth-cognito/src/lib.rs
crates/hearth-ctl/src/spawn_wasm.rs
crates/hearth-types/src/wasm.rs
guest/rust/hearth-guest/src/lib.rs
guest/rust/hearth-test-wasm/Cargo.toml
guest/rust/hearth-test-wasm/src/lib.rs

- adds the `entrypoint` field to `WasmSpawnInfo` so that multiple entrypoints can be called on a single Wasm module.
- adds the `process::this_lump()` ABI call so that processes can retrieve the lump IDs of the lumps that they were spawned with.
- updates the `hearth-test-wasm` crate with a modified recursive merge sort that switches to bubble sort on chunks smaller than 33 elements. this tests both the concurrency capabilities of Hearth and its message passing against a (relatively) compute-intensive parallel operation.

Multiple entrypoints + `this_lump()`

---

Cargo.toml
crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-core/src/process/context.rs
crates/hearth-core/src/process/mod.rs
crates/hearth-init/Cargo.toml
crates/hearth-init/src/lib.rs
crates/hearth-server/Cargo.toml
crates/hearth-server/src/main.rs

Adds the `hearth-init` crate, hooks, and makes server networking and client networking depend on the init system to provide root capabilities for each of their connections.

Basic init system API

---

crates/hearth-client/src/main.rs
crates/hearth-cognito/examples/run_wasm.rs
crates/hearth-cognito/src/lib.rs
crates/hearth-core/src/runtime.rs
crates/hearth-fs/src/lib.rs
crates/hearth-init/src/lib.rs
crates/hearth-rend3/src/lib.rs
crates/hearth-server/src/main.rs

The `Plugin` trait had some non-useful semantics, namely the `run` method,
which was virtually never used. I've replaced it with the `finish` method,
which takes ownership of the plugin and gives it a `RuntimeBuilder` to finalize
the building of a plugin after it's been configured by other plugins.

Refactor plugins API

---

crates/rend3-alacritty/Cargo.toml
crates/rend3-alacritty/examples/demo.rs
crates/rend3-alacritty/src/gpu.rs
crates/rend3-alacritty/src/lib.rs
crates/rend3-alacritty/src/terminal.rs
crates/rend3-alacritty/src/text.rs

Big refactors and improvements to `rend3-alacritty`.
- better color usage
- abstract and organize terminal management
- orbit controls in demo (closes #37)
- font-based cell metrics
- support state + resizing
- background opacity
- transform terminals with state
- dynamic terminal colors
- configure the shell to run with platform-specific autoselect as fallback

Alacritty improvements

---

crates/rend3-alacritty/src/terminal.rs

Closes #173.
I'll follow this up with an issue to manage the distribution of Alacritty terminfo like discussed, but the `setup_env` function falls back to `xterm-256color` if it can't find Alacritty's, so I think that we're ok to use this in main for now.

alacritty: setup env vars

---

crates/hearth-ipc/Cargo.toml

Fixes a local build failure where `hearth-ipc` was failing to import `tokio::sync` since the "sync" feature on Tokio wasn't enabled.
Not sure why this wasn't an issue in CI before, but I figure that it's because I updated my Rust version and that somehow affects feature directives in dependencies. Best to get this patched upstream ASAP.

ipc: enable tokio sync feature

---

crates/hearth-ctl/Cargo.toml
crates/hearth-ctl/src/main.rs

yacexits requires a clang system dependency to compile on at least Mac, so we're going to substitute it for something else. I'm removing it for now until we can decide what the new best way to return standard error codes is.

ctl: remove yacexits dep

---

crates/hearth-client/src/window.rs

Fixes some flickering I was experiencing while running multiple terminal emulators.

client: switch from Immediate to Fifo present mode

---

.github/workflows/depgraph.yml

Running the depgraph update workflow in PRs is causing merge conflicts and invalidating CI passes, making it difficult to get PRs that update the depgraph merged. Since the depgraph visualization only needs to be updated on the main branch, we've decided to disable it for PRs.

github: update depgraph on main push only

---

.github/workflows/pr.yml

Hopefully makes it less of a pain to track whether commits pass CI or not by ALWAYS running CI regardless of which files are changed.

github: always trigger PR CI

---

.github/workflows/depgraph.yml
Cargo.toml
tools/depgraph/Cargo.toml
tools/depgraph/src/main.rs

I made a new `hearth-depgraph` crate that generates a depgraph in `.dot` format just like the `cargo-depgraph` crate does, but it's much simpler, sets different attributes in the resulting `.dot` file, and most importantly, clusters together each crate based on its subdirectory in Hearth's repository.
I've also set up CI to use it instead of `cargo-depgraph`.

Custom depgraph

---

kindling/host/src/lib.rs

Adds doc comments to the macros in kindling-host

kindling-host: macro doc comments

---

plugins/terminal/src/terminal.rs

Before:
After:
I'm not sure there was ever a full cell Unicode character to begin with.

terminal: don't skip drawing foregrounds of 'full' cells

---

plugins/terminal/src/terminal.rs

Fixes a graphical bug in terminal rendering where the terminal would size the grid to exceed the available panel size if the padding is low, leading to the padding being drawn on top of the grid.
Before:
After:

terminal: ceil->floor available panel size

---

guest/rust/hearth-guest/src/lib.rs
kindling/host/src/lib.rs
kindling/host/src/renderer.rs
kindling/services/skybox/src/lib.rs

kindling-host: renderer bindings
