hearth-rs/hearth

Cargo.toml
crates/hearth-client/Cargo.toml
crates/hearth-client/src/main.rs
crates/hearth-core/Cargo.toml
crates/hearth-core/src/lib.rs
crates/hearth-server/Cargo.toml
crates/hearth-server/src/main.rs

Set up `hearth-core`

---

crates/hearth-rpc/src/lib.rs

rpc: object-oriented process API

---

crates/hearth-client/src/main.rs

client: adds DNS resolution for --server

---

crates/hearth-core/Cargo.toml
crates/hearth-core/src/asset.rs
crates/hearth-core/src/lump.rs
crates/hearth-core/src/process.rs
crates/hearth-core/src/runtime.rs
crates/hearth-macros/src/lib.rs
crates/hearth-wasm/Cargo.toml
crates/hearth-wasm/src/lib.rs

Adds better log messages and error handling to:
- `GuestMemory` initialization and fetching (look ma, no panics! wasm host functions should never crash now)
- asset loading
- lump uploading and downloading
- message sending
- all of `RemoteProcess` (also dies when it's supposed to now)
- runtime startup

Better errors

---

CONTRIBUTORS.md

- contributors: add Sasha
- contributors: add Malek
- contributors: add Emma
- contributors: fix Sasha's website link
- contributors: add iris

contributors: add up-to-date contributor acknowledgments

---

.github/workflows/pr.yml
CONTRIBUTORS.md
README.md
crates/hearth-ctl/src/list_peers.rs

.github: use nightly toolchain in rustfmt job

---

crates/hearth-ctl/src/list_processes.rs
crates/hearth-ctl/src/main.rs

ctl: list processes

---

crates/hearth-server/src/main.rs

server: headless mode

---

crates/hearth-ctl/src/main.rs

ctl: remove placeholder command

---

crates/hearth-client/src/main.rs
crates/hearth-core/Cargo.toml
crates/hearth-core/src/lib.rs
crates/hearth-core/src/runtime.rs
crates/hearth-server/src/main.rs

- core: add config file support
- server: load config file and support config arg
- client: load config file and support config arg

Config files

---

crates/hearth-types/src/lib.rs
crates/hearth-types/src/wasm.rs

types: add wasm submodule and WasmSpawnInfo

---

crates/hearth-core/src/process.rs

Fixes #91. My guess was right!

core: link RemoteProcess locally, not remotely

---

README.md

closes #99 
closes #98 
closes #97 
closes #80

Readme roadmap updates

---

CONTRIBUTORS.md

contributors: fix my name

---

.github/workflows/pr.yml

github: fix rustfmt

---

.github/workflows/pr.yml

github: only trigger PR checks on Rust changes

---

DESIGN.md
README.md
crates/hearth-cognito/Cargo.toml
crates/hearth-cognito/src/lib.rs
crates/hearth-core/src/asset.rs
crates/hearth-core/src/lib.rs
crates/hearth-core/src/runtime.rs

Greatly redesigns the purpose of assets. The design document and road map have been updated, as well as the core APIs.

Better assets

---

crates/hearth-cognito/src/lib.rs
crates/hearth-core/src/pubsub.rs
crates/hearth-types/src/lib.rs

types: display processids

---

crates/hearth-ctl/src/list_peers.rs
crates/hearth-ctl/src/list_processes.rs
crates/hearth-ctl/src/main.rs
crates/hearth-types/src/lib.rs

ctl: command output cleanup

---

crates/hearth-ctl/Cargo.toml
crates/hearth-ctl/src/kill.rs
crates/hearth-ctl/src/list_peers.rs
crates/hearth-ctl/src/list_processes.rs
crates/hearth-ctl/src/main.rs
crates/hearth-ctl/src/run_mock_runtime.rs
crates/hearth-ctl/src/spawn_wasm.rs

closes #131 
closes #77 
This pr still needs a lot of work before it can be merged. I would also like to have someone look over my use of error codes and make sure I used the right ones.

ctl: improve error handling

---

README.md
crates/font-mud/examples/pack_mononoki.rs
crates/font-mud/src/glyph_atlas.rs
crates/font-mud/src/glyph_bitmap.rs
crates/rend3-alacritty/examples/demo.rs
crates/rend3-alacritty/src/lib.rs

Closes #55.
- font-mud: pack glyphs but defer generation
- alacritty: async glyph gen + upload
- readme: check off async glyphs from roadmap

Asynchronous glyph loading

---

crates/hearth-client/src/main.rs
crates/hearth-cognito/examples/run_wasm.rs
crates/hearth-cognito/src/lib.rs
crates/hearth-core/src/process/factory.rs
crates/hearth-core/src/process/remote.rs
crates/hearth-core/src/runtime.rs
crates/hearth-ctl/src/main.rs
crates/hearth-server/src/main.rs
crates/hearth-types/src/lib.rs

remove peer id

---

crates/hearth-cognito/src/lib.rs
crates/hearth-core/Cargo.toml
crates/hearth-core/src/lib.rs
crates/hearth-core/src/utils.rs
crates/hearth-fs/src/lib.rs

I made this for two reasons:
1. Easier writing of native services
2. An abstraction layer between message-passing and event handling (to accommodate mailboxes)

Utilities for writing native services

---

crates/hearth-cognito/src/lib.rs
guest/rust/hearth-guest/src/lib.rs

guest: panic handler

---

crates/rend3-alacritty/examples/demo.rs
crates/rend3-alacritty/src/terminal.rs

- alacritty: padding + all cursors (closes #40)
- alacritty: cleaner font metrics
- alacritty: WIP strikeouts + underlines
- alacritty: underlines + strikethrus (closes #53)

alacritty: shapes

---

crates/hearth-client/src/main.rs

client: serverless mode + refactor into plugin

---

crates/hearth-client/src/main.rs
crates/hearth-client/src/window.rs

I cleaned up some of the window management code because I found it pretty difficult to work with. I also went ahead and fixed #166.

client: refactor windowing code

---

.github/workflows/pr.yml

github: add Mac to build matrix

---

crates/hearth-core/src/registry.rs
crates/hearth-wasm/examples/run_wasm.rs

core: fix registry exports

---

crates/hearth-fs/src/lib.rs
crates/hearth-types/src/fs.rs

handle fs errors

---

.helix/config.toml

helix: add kindling/build workspace root

---

Cargo.toml
core/schema/Cargo.toml
core/schema/src/canvas.rs
core/schema/src/lib.rs
main/client/Cargo.toml
main/client/src/main.rs
plugins/canvas/Cargo.toml
plugins/canvas/src/lib.rs
plugins/canvas/src/shaders.wgsl

Adds "canvas" support: rectangular RGB textures that can be efficiently and dynamically updated by the guest.

Add `hearth-canvas`

---

plugins/canvas/src/lib.rs

Fixes Z-sorting issues against the terminals.

canvas: enable canvas depth write

---

README.md

Adds some useful shields from shields.io to our README, hopefully increasing the number of people that join our chats from Discord.

readme: add shields

---

main/client/src/window.rs

Closes #262.
I implement a different solution here than mentioned in the original issue, but... oh well. This scales better.

client: broadcast window state on new subscribers

---

guest/rust/hearth-guest/src/lib.rs
kindling/host/src/canvas.rs
kindling/host/src/debug_draw.rs
kindling/host/src/lib.rs
kindling/host/src/terminal.rs
kindling/host/src/time.rs
kindling/host/src/window.rs
kindling/services/window-test/src/lib.rs

Resolves  https://github.com/hearth-rs/hearth/issues/278
My first pr, please read it thoroughly, i probably didn't know what i was doing

guest: change send/recv to be json by default and add send_raw/recv_raw

---

core/runtime/src/process.rs
core/runtime/src/runtime.rs
core/runtime/src/utils.rs
core/schema/Cargo.toml
core/schema/src/lib.rs
guest/rust/Cargo.toml
guest/rust/hearth-guest/Cargo.toml
guest/rust/hearth-guest/src/lib.rs
guest/rust/hearth-guest/src/subscriber.rs
kindling/Cargo.toml
kindling/host/Cargo.toml
kindling/host/src/lib.rs
kindling/services/window-test/src/lib.rs
plugins/canvas/src/lib.rs
plugins/init/src/lib.rs
plugins/wasm/src/lib.rs

Route process logs through tracing

---

kindling/Cargo.toml
kindling/schema/Cargo.toml
kindling/schema/src/lib.rs
kindling/utils/src/registry.rs

Closes #235.
- kindling-schema: add initial crate
- kindling-utils: remove TODO note to add RegistryConfig to schema

Add kindling-schema crate

---

main/client/src/main.rs
main/server/src/main.rs

Merge prior to #231
- client: give init a default value
- server: give init a default value

main: Default value for init on binaries

---

README.md

readme: Running instructions
